### ISSUE TITLE
Kanbard board

### ISSUE THREAD

**Issue by christianonoh** [christianonoh/space-travel#25]
## We are a team of two, @christianonoh & @zamcham 
https://github.com/christianonoh/space-travel/projects/1

**Comment by topeogunleye** [comment]
@christianonoh, @zamcham. The link you submitted for your kanban board project is wrong.  Please find below the correct link:

https://github.com/christianonoh/space-travel/projects/1

**Comment by zamcham** [comment]
> @christianonoh, @zamcham. The link you included in your comment as project link is wrong. Please find below the correct link: @christianonoh, @zamcham. Kindly edit your comment to update your project link. https://github.com/christianonoh/space-travel/projects/1

Thank you @topeogunleye the link is updated now!

**Comment by topeogunleye** [comment]
> > @christianonoh, @zamcham. The link you included in your comment as project link is wrong. Please find below the correct link: @christianonoh, @zamcham. Kindly edit your comment to update your project link. https://github.com/christianonoh/space-travel/projects/1
> 
> Thank you @topeogunleye the link is updated now!

ýou're welcome 😄

**Comment by topeogunleye** [comment]
Hi @christianonoh, @zamcham, 

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟

![wiserhood-cheers](https://user-images.githubusercontent.com/52934128/180645705-4076a14b-d85b-4173-833e-300c532ceaa6.gif)

## To highlight :champagne: 
- Set up Kanban board successfully. ✔️ 
- Tasks are distributed equally amongst team members. ✔️ 
- All cards are assigned to team members ✔️ 
- Students' board is a copy of template board ✔️ 

## Optional suggestions
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
